In [1]:
import numpy as np
import sys

In [2]:
np.array([1,2,3],dtype="int8")

array([1, 2, 3], dtype=int8)

In [3]:
a = np.array([1,2,3])
b = np.array([3,4,5])
print(a)
print(a*b)

[1 2 3]
[ 3  8 15]


In [44]:
# 2d sarray
c = np.array([[1,2,3],[4,5,6]])
#get dimension
print(c.ndim)
#get shape
print(c.shape)
#get data type
print(c.dtype)
d = np.array([1,4,6],dtype='int32') # we can specify which data type we want
e = np.array([4,5,6,7,8,9],dtype='int8')

print(c)
print(d)
print(e)


2
(2, 3)
int32
[[1 2 3]
 [4 5 6]]
[1 4 6]
[4 5 6 7 8 9]


In [45]:
# get data size (bytes)
print(d.itemsize)
print(e.itemsize)

4
1


In [46]:
#get  size (number of elements)
print(d.size)
print(e.size)

3
6


In [11]:
# get total size = itemsize * size
print(d.nbytes)
print(e.nbytes)

12
6


In [12]:
# slicing in numpy
# get specific element with certain index
print(c[1,2]) # matrix c index ke 1, lalu index 2
#get specific row
print(c[0,:]) # return whole 1st row
# get specific column
print(c[:,1])

6
[1 2 3]
[2 5]


In [47]:
f = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20],[21,22,23,24,25,26,27,28,29,30]])
# array[row , startindex:endindex:stepsize]
print(f[0,1:6:2])
print(f[2,::3])
print(f.size)

[2 4 6]
[21 24 27 30]
30


In [14]:
#change value
f[0,0] = 5  # 1 swapped with 5
print(f[0]) 

f[0,:] = 23 # mengubah baris ke 0, menjadi 23 semuanya
print(f[0])

[ 5  2  3  4  5  6  7  8  9 10]
[23 23 23 23 23 23 23 23 23 23]


In [15]:
# 3D array
g = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 2x2x3
print(g)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
# get specific element
print(g[0,1,1]) # lebar 0, row 1, column 1

5


In [17]:
# replace
g[:,1,1] = 9
print(g)

[[[ 1  2  3]
  [ 4  9  6]]

 [[ 7  8  9]
  [10  9 12]]]


In [18]:
# All zero matrix
zero = np.zeros((2,3,4)) # leabr 2, baris 3, kolom 4
print(zero)

zero2 = np.zeros((3,4)) # baris 3, kolom 4
print(zero2)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
# All 1 matrices
one = np.ones((2,3,4))
print(one)
one2 = np.ones((3,4), dtype='int16')
print(one2)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
# All (any number) matrices np.full((size),parameter,dtype='float32')
full = np.full((2,2),99)
print(full)

[[99 99]
 [99 99]]


In [21]:
# full 2 and 3 will return exactly same matrix
full2 = np.full(a.shape,65)
full3 = np.full_like(a,65)
print(full2)
print(full3)

[65 65 65]
[65 65 65]


In [22]:
# full random decimal numbers
h = np.random.rand(2,4)
print(h)
i = np.random.random_sample(a.shape)
print(i)

[[0.76349061 0.37783321 0.49884717 0.78553732]
 [0.99661148 0.52141997 0.91266765 0.42906818]]
[0.2707949  0.96597417 0.66079302]


In [50]:
#  random integer values
j = np.random.randint(7) # random integer bertween 0-7
print(j)
j = np.random.randint(5,size=(3,3)) # random integer 0-5, size 3x3
print(j)
j = np.random.randint(-10,10,size=(3,4)) # random int -10 until 10, size 3x4
print(j)

4
[[3 1 4]
 [4 3 0]
 [0 3 1]]
[[ -1 -10   5  -4]
 [  6   0   7   9]
 [  8   7  -6   0]]


In [51]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
# repeating array
arr = np.array([1,2,3])
repeat1 = np.repeat(arr,3) # repeatin array 3times
print(repeat1)

arr = np.array([[1,2,3]]) # 2d ,matrix
repeat1 = np.repeat(arr,3,axis=0)
print(repeat1)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [61]:
# make nice matrix
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 1
print(z)

output[1:4,1:4] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
